version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean install -DskipTests
artifacts:
  files:
    - target/aws-microservice-deploy-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - start.sh
    - stop.sh
  discard-paths: yes