spring:
  application:
    name: uaa-service
  datasource:
    url: jdbc:mysql://avengers-db-instance.chszpfohfria.us-east-1.rds.amazonaws.com/forFun
    username: root
    password: rootlibrary
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true


server:
  port: 8080

security:
  basic:
    enabled: false
